# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Gas meter to HomA MQTT
version: 1.0.0
slug: gas-meter-homa
description: A gas meter monitor for the HomA MQTT framework
url: https://github.com/hass-hmueller01/addon-gas-meter-homa
# remove the image tag if you want to use it as a local add-on
image: "hmueller01/homeassistant-addon-gas-meter-homa-{arch}" # on https://hub.docker.com
arch:
  - aarch64
  - amd64
init: false
options:
  device_name: "Gas Meter"
  gpio_pin: 17
  calorific_value: 11.4
  homa_system_id: "123456-gas-meter"
  homa_room: "Sensors"
  hass_area: "Energie"
  debug: false
schema:
  device_name: "str"
  gpio_pin: "int"
  calorific_value: "float"
  homa_system_id: "str"
  homa_room: "str"
  hass_area: "str"
  mqtt_host: "str?"
  mqtt_port: "int?"
  mqtt_user: "str?"
  mqtt_password: "str?"
  mqtt_ca_certs: "str?"
  debug: "bool"
services:
  - mqtt:need
gpio: true
privileged:
  - SYS_RAWIO
devices:
  - /dev/gpiochip0
  - /dev/gpiochip1
  - /dev/gpiochip2
  - /dev/gpiochip3
  - /dev/gpiochip4
  - /dev/gpiochip5
  - /dev/gpiochip6
  - /dev/gpiochip7
  - /dev/gpiochip8
  - /dev/gpiochip9
  - /dev/gpiochip10
  - /dev/gpiochip11
  - /dev/gpiochip12
  - /dev/gpiochip13
  - /dev/gpiochip14
  - /dev/gpiochip15
